### ISSUE TITLE
maven plugin doesn't exist in maven central

### ISSUE THREAD

**Issue by antogerva** [jhorstmann/i18n#3]
Please, I believe the project could get more interest if a repo existed:
Here's a procedure about how to proceed:
http://jroller.com/holy/entry/releasing_a_project_to_maven
http://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/#.VF_mcPmG8b0
edit: Removed old links.

**Comment by jhorstmann** [comment]
Released version 0.1 to central. Please not that the groupId changed to just net.jhorstmann.
